add s3path
awslabs/s3-connector-for-pytorch pull request #291
Opened 2024-12-27 00:05 UTC by ryxli

## Description

Provide implementation of Pathlib abc with S3 as the backing file store. Utilizes how s3connector exposes read and write streams via Mountpoint CRT client.

## Additional context

This will be utilized to easily integrate with Pytorch DCP implementations such as Megatron-Core distributed checkpointing
https://docs.nvidia.com/megatron-core/developer-guide/latest/api-guide/dist_checkpointing.html

- [ ] I have updated the CHANGELOG or README if appropriate

## Related items

## Testing

--------
By submitting this pull request, I confirm that my contribution is made under the terms of BSD 3-Clause License and I agree to the terms of the [LICENSE](https://github.com/awslabs/s3-connector-for-pytorch/blob/main/LICENSE).

2025-01-03 01:35 UTC, ryxli commented on s3torchconnector/src/s3torchconnector/s3path.py
> +    def stat(self, *, follow_symlinks=True):
```
    def stat(self, *, follow_symlinks=True):
        try:
            info = self._client.head_object(self.bucket, self.key.rstrip("/"))
            mode = stat.S_IFREG
        except S3Exception as e:
            listobj = next(self._client.list_objects(self.bucket, self.key + "/"))
            if len(listobj.object_info) > 0:
                info = SimpleNamespace(size=0, last_modified=None)
                mode = stat.S_IFDIR
            else:
                error_msg = f"No stats available for {self}; it may not exist."
                raise FileNotFoundError(error_msg) from e
        return os.stat_result(
            (
                mode,  # mode
                None,  # ino
                "s3://",  # dev,
                None,  # nlink,
                None,  # uid,
                None,  # gid,
                info.size,  # size,
                None,  # atime,
                info.last_modified,  # mtime,
                None,  # ctime,
            )
        )

```

2025-01-06 16:29 UTC, IsaevIlya reviewed
Thank you for your contribution to s3-connector-for-pytorch! Please, give us a few days for a review.

2025-01-07 15:51 UTC, IsaevIlya requested changes
Thank you for your contribution implementing S3Path. To maintain our high quality standards, could you please enhance your changes with:

1. Integration tests using a real S3 bucket
2. Error logging for key operations
3. Docstrings explaining behavior, especially where it differs from standard pathlib
4. Brief section in README.md with a usage example

Please let me know if you need any clarification or assistance with these additions.

2025-01-07 15:51 UTC, IsaevIlya commented on s3torchconnector/tst/unit/test_s3path.py
> +
Could it be possible to add unit tests for `with_name`, `rmdir`, `unlink`, `mkdir` too?

2025-01-07 21:08 UTC, ryxli commented on s3torchconnector/src/s3torchconnector/s3path.py
> +        if self.is_dir():
s3 objects and folders can both exist with the same name without conflicts
<img width="1421" alt="Screenshot 2025-01-07 at 1 08 02 PM" src="https://github.com/user-attachments/assets/e5d7c09b-56ac-44ea-8492-b87822c0b3d0" />

2025-01-07 21:40 UTC, ryxli commented on s3torchconnector/src/s3torchconnector/s3path.py
> +        return os.stat_result(
Agree, can add.

One issue here that I don't have an answer for is usage for example in SPMD. since class attributes are isolated per process, without communication there is still some ineffiency there if some ranks call stat on the same file

2025-01-07 21:41 UTC, ryxli commented on s3torchconnector/src/s3torchconnector/s3path.py
> +                    listobjs = list(self._client.list_objects(self.bucket, self.key))
Is max_keys=1 enough?

2025-01-07 23:03 UTC, ryxli commented on s3torchconnector/tst/unit/test_s3path.py
> +
added

2025-01-08 14:52 UTC, IsaevIlya commented on s3torchconnector/src/s3torchconnector/s3path.py
> +                    listobjs = list(self._client.list_objects(self.bucket, self.key))
If we know that there are no other objects with the name equals to `self.key`, then yes it should be enough.

2025-01-08 14:56 UTC, IsaevIlya commented on s3torchconnector/src/s3torchconnector/s3path.py
> +        return os.stat_result(
Could we start with caching `stat` per instance only and passing caching configuration through constructor? I don't know pattern of using Path like primitives, would it be too cumbersome to turn-off cache via constructor? If we generally create new instances of S3Path from another instances of S3Path, then we can just pass the cache settings between them.

2025-01-24 23:01 UTC, ryxli commented on s3torchconnector/tst/unit/test_s3path.py
> +        time.sleep(1)  # S3 needs some time to register the deletion
I also assumed the same, but it seemed like tests wouldn't pass without the sleep.

Maybe some limitation of the MockS3Client?

2025-01-24 23:02 UTC, ryxli commented on s3torchconnector/tst/unit/test_s3path.py
> +    time.sleep(1)  # S3 needs some time to register the deletion
I also assumed the same, but it seemed like tests wouldn't pass without the sleep.

Maybe some limitation of the MockS3Client?

2025-01-27 16:42 UTC, IsaevIlya commented on s3torchconnector/tst/unit/test_s3path.py
> +        time.sleep(1)  # S3 needs some time to register the deletion
Interesting. I will take a look into it.

2026-05-22 15:30 UTC, jet-tong commented
Hi @ryxli, apologies for leaving this PR open so long. Thank you for the contribution and for addressing the review feedback.

We've decided to close this PR for now. Since S3Path was primarily motivated by Megatron-Core support, we'd want to maintain Megatron integration tests to properly validate it - which is not something we plan to take on right now. [Megatron's Multi-Storage Client](https://github.com/NVIDIA/multi-storage-client) now also provides a pathlib-compatible S3 interface that covers this use case, which reduces the urgency for this project to adopt S3Path.

We appreciate the effort you put into this. Please feel free to open an issue if you'd like to revisit.

2026-05-22 15:30 UTC, closed without merging